import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/mode-toggle";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
    title: "Persona.fm",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div>
                        <Nav />
                    </div>
                    <div className="container mx-auto">{children}</div>
                    <div>
                        <Footer />
                    </div>
                    <div className="fixed bottom-4 right-4">
                        <ModeToggle />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
